### ISSUE TITLE
Feature: autorebase concurrent mode

### ISSUE THREAD

**Issue by splincode** [peter-evans/rebase#101]
https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration

![image](https://user-images.githubusercontent.com/12021443/137297327-b262ad67-e1ca-46ea-ab2f-4a7121889d0b.png)

Well, we had to remove autorebase:
https://github.com/TinkoffCreditSystems/taiga-ui/pull/883#pullrequestreview-779554189

![image](https://user-images.githubusercontent.com/12021443/137297682-c221119b-9a24-44cc-8d17-45353c767380.png)

we have a lot of branches, and now all our assemblies are queued because they do not have time to be processed

**Comment by peter-evans** [comment]
I've add the `include-labels` feature you asked for now, so I'll close this for now. Hopefully you can use that feature to control when pull requests are rebased a little easier.
