### ISSUE TITLE
GitHub Actions: Deprecating save-state and set-output commands

### ISSUE THREAD

**Issue by borisceranic** [peter-evans/rebase#119]
Hi @peter-evans,

First off, thank you for this amazing action you built! It's really helpful for maintaining a rebase-centric workflow within our dev organisation.

Now, the issue. Yesterday, GitHub published a deprecation notice for "save-state", that now results in a warning emitted by a workflow that uses this action:

    Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using
    Environment Files. For more information see: https://...[link moved below]

<img width="350" alt="Screenshot 2022-10-12 at 18 02 54" src="https://user-images.githubusercontent.com/53285/195392573-ab048ea1-f5f1-4521-ab1b-186ca14e968b.png">

Here's a link from the warning message: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Is there any chance to update the action code to make use of the recommended mechanism instead of the deprecated one?

TIA!

**Comment by peter-evans** [comment]
Hi @borisceranic 

Sure. I'm planning to update all of the actions I maintain soon.

**Comment by peter-evans** [comment]
Released as `v2.0.1` / `v2`.
