### ISSUE TITLE
Rebase not triggering github actions

### ISSUE THREAD

**Issue by splincode** [peter-evans/rebase#82]
https://github.com/Angular-RU/angular-ru-sdk/runs/3673955150

Hello, I add your github action and this is not triggering pipelines again

![image](https://user-images.githubusercontent.com/12021443/134326887-67a9af1c-adf2-4c42-a0c6-2cc1cc92e33b.png)

Please, what's happen?

**Comment by haarts** [comment]
What happened??!?
