### ISSUE TITLE
Cannot read property 'url' of null

### ISSUE THREAD

**Issue by splincode** [peter-evans/rebase#83]
```ts
name: Rebase all pull requests on push to the base branch

on:
    push:
        branches: [main]

jobs:
    rebase:
        runs-on: ubuntu-latest
        steps:
            - uses: peter-evans/rebase@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  base: main
```

in main branch

https://github.com/TinkoffCreditSystems/taiga-ui/runs/3674687477

![image](https://user-images.githubusercontent.com/12021443/134338727-bc39c42b-4d95-449a-9427-7cf5f5f2bc14.png)

**Comment by peter-evans** [comment]
@splincode Thank you for reporting this issue. I've fixed it in the latest release and `v1` should be working now.

**Comment by splincode** [comment]
@peter-evans hello, i try again

https://github.com/TinkoffCreditSystems/taiga-ui/runs/3688716874
