### ISSUE TITLE
Add option to skip PRs based on a label

### ISSUE THREAD

**Issue by lucacome** [peter-evans/rebase#92]
It would be very useful to have an option to skip rebasing a PR if it has a specific label.

**Comment by peter-evans** [comment]
Hi @lucacome 

Thanks for the feature idea. I'll take a look at adding this.

**Comment by peter-evans** [comment]
Released `v1.1.0` / `v1` with this feature. Thanks!

**Comment by lucacome** [comment]
that was fast! thanks! 🎉
